### ISSUE TITLE
question on extract prior mesh

### ISSUE THREAD

**Issue by ning1203** [zjy526223908/DreamEditor#10]
Is the mesh extracted by  [  python train_init_nerf.py -O --workspace ./res/dtu_scan105-grid  --test --save_mesh] the same as the mesh in given data?

I feel confused that the doll.ply from the given data is only 2.4M, but the mesh_nocolor.ply which is extracted by  [python train_init_nerf.py -O --workspace ./res/dtu_scan105-grid  --test --save_mesh]   is 154M.

And when I used extracted mesh mesh_nocolor.ply and run 
[python3 train_editing.py --test --save_vedio \
--far_point_thresh 0.05 \
--R_path data/dtu_scan105/Orient_R.npy \
--load_path res_model/doll/sunglasses/df_ep0100.pth \
--prior_mesh res_model/doll/sunglasses/mesh_nocolor.ply \
--text "a photo of a <ktn> plush toy wearing black sunglasses" \
--radius_range 0.5 0.5 --fovy_range 50 50 --pose_sample_strategy '360' \
--phi_range -45 45 --theta_range 75 75 \
--workspace ./res_doll/sunglasses]，
the error shows that
 [[WARN] No checkpoint found, model randomly initialized.
loading pre mesh net
Traceback (most recent call last):
  File "train_editing.py", line 189, in <module>
    trainer = Trainer('df', opt, model, guidance, background_model, opt, device=device, workspace=opt.workspace,
  File "/data_sobig/huimin/step1DreamEditor-main/nerf/utils_editing.py", line 220, in __init__
    self.load_checkpoint(checkpoint=self.opt.load_path, model_only=True)
  File "/data_sobig/huimin/step1DreamEditor-main/nerf/utils_editing.py", line 1095, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
  File "/data_new/huimin/anaconda3/envs/dreameditor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
	size mismatch for mesh_vertices: copying a param with shape torch.Size([38690, 3]) from checkpoint, the shape in current model is torch.Size([4145977, 3]).
	size mismatch for mesh_triangles: copying a param with shape torch.Size([76383, 3]) from checkpoint, the shape in current model is torch.Size([8125394, 3]).
	size mismatch for mesh_vertices_offset: copying a param with shape torch.Size([38690, 3]) from checkpoint, the shape in current model is torch.Size([4145977, 3]).
	size mismatch for geometry_features: copying a param with shape torch.Size([38690, 128]) from checkpoint, the shape in current model is torch.Size([4145977, 128]).
	size mismatch for color_features: copying a param with shape torch.Size([38690, 128]) from checkpoint, the shape in current model is torch.Size([4145977, 128]).
]

I doubt the extracted mesh is not right, but I do not know how to fix.

Thank u for your help!

**Comment by jingwu2121** [comment]
Hi, did you find the solution, I am also confused about this problem. The data is so confusing. By the way, do you know how to obtain `editing_region_info.npy` and `editing_region_mask.ply` in the `locating` folder in data folder? I search, but seems I haven't found any code to generate these 2 yet. Thank you so much!! :-)
